logo = true
logoText = "Clusternet"
logoType = "short" # long, short -> short: squre shape includes logo text, long: rectangle shape not includes logo text
description = "The Clusternet project documentation site." # for SEO
editBaseURL = "https://github.com/clusternet/website/edit/main"
themeOptions = ["dark", "light"] # select options for site color theme ["dark","light"]

useFaviconGenerator = true # https://www.favicon-generator.org/

wideViewAsDefault = true

enableWideBlogSwitch = true
enableTocSwitch = true
enableLandingBackground = true
enableSearch = true
enableSearchHighlight = true
enableLangChange = false
enableDarkMode = false
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = true
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = false

paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/clusternet/clusternet"

enableComment = false
